# Generated by Django 4.0.3 on 2022-04-13 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='TVM', max_length=100)),
                ('state', models.CharField(default='KL', max_length=6)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(default='UNKNOWN', max_length=25)),
                ('date', models.DateField(blank=True, null=True)),
                ('manganese', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('nitrate', models.FloatField(default=0)),
                ('arsenic', models.FloatField(default=0)),
                ('fluoride', models.FloatField(default=0)),
                ('chloride', models.FloatField(default=0)),
                ('sulphate', models.FloatField(default=0)),
                ('copper', models.FloatField(default=0)),
                ('tds', models.FloatField(default=0)),
                ('ph', models.FloatField(default=0)),
                ('hardness', models.FloatField(default=0)),
                ('alkalinity', models.FloatField(default=0)),
                ('turbidity', models.FloatField(default=0)),
                ('coliform', models.FloatField(default=0)),
                ('ecoil', models.FloatField(default=0)),
                ('wqi', models.FloatField(default=0)),
                ('isPhyContaminated', models.BooleanField(default=False)),
                ('isCheContaminated', models.BooleanField(default=False)),
                ('isBioContaminated', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.location')),
            ],
            options={
                'verbose_name': 'Test Sample',
                'verbose_name_plural': 'Test Samples',
                'db_table': 'sample',
            },
        ),
    ]
