# Generated by Django 4.0.3 on 2022-04-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
