# Generated by Django 4.0.3 on 2022-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_testsample_alkalinity_alter_testsample_arsenic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsample',
            name='alkalinity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='arsenic',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='chloride',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='copper',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='fluoride',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='hardness',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='manganese',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='nitrate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='sulphate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='tds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='turbidity',
            field=models.FloatField(default=0),
        ),
    ]
