# Generated by Django 4.0.3 on 2022-03-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_testsample_alkalinity_alter_testsample_arsenic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsample',
            name='coliform',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='ecoil',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='wqi',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
