# Generated by Django 4.0.3 on 2022-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_testsample_coliform_alter_testsample_ecoil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsample',
            name='coliform',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='ecoil',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='testsample',
            name='wqi',
            field=models.FloatField(default=0),
        ),
    ]
