# Generated by Django 4.0.3 on 2022-03-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_alter_testsample_coliform_alter_testsample_ecoil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alkalinity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='arsenic',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='chloride',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='coliform',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='copper',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='ecoil',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='firstRecorded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='fluoride',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='hardness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='iron',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='lastRecorded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='manganese',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='nitrate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='ph',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='sulphate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='tds',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='totalSamples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='trends',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='turbidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='wqi',
            field=models.FloatField(default=0),
        ),
    ]
